name: EconomyCasino
main: onebone\economycasino\EconomyCasino
version: "2.0.1"
api: 5.0.0

depend: [EconomyAPI]
author: onebone

commands:
 casino:
  description: EconomyCasino command
  usage: /casino
  permission: economycasino.command.casino
permissions:
 economycasino.command:
  description: Allows player to use all of casino command
  default: op
  children:
   economycasino.command.casino:
    description: Allows player to use /casino command
    default: true
