name: EconomyProperty
main: onebone\economyproperty\EconomyProperty
version: "2.0.1"
api: 5.0.0

depend: [EconomyAPI]
author: onebone

commands:
  property:
   description: EconomyProperty command
   usage: /property
   permission: economyproperty.command.property

permissions:
 economyproperty.command:
  description: Allows player to use all of property command
  default: op
  children:
   economyproperty.command.property:
    description: Allows player to use /property command
    default: true