name: EconomyShop
main: onebone\economyshop\EconomyShop
version: "2.0.1"
api: 5.0.0

depend: [EconomyAPI]
author: onebone

commands:
 shop:
  description: EconomyShop command
  usage: /shop
  permission: economyshop.command.shop
permissions:
 economyshop.command:
  description: Allows player to use all of shop command
  default: op
  children:
   economyshop.command.shop:
    description: Allows player to use /shop command
    default: true
