name: EconomyShop
<<<<<<< HEAD
=======
version: "2.0.7"
api: 5.0.0

>>>>>>> 1011d39ed1ea3ab6f6329818ddb2078ec03b1144
main: onebone\economyshop\EconomyShop
version: "2.0.0"
author: onebone
api: 5.0.0
depend: [EconomyAPI]

commands:
  shop:
    description: "Shop management command"
    usage: "/shop <create|remove>"
    permission: economyshop.command

permissions:
  economyshop:
    default: op
    description: "Allows access to all EconomyShop features"
    children:
      economyshop.command:
        default: true
        description: "Allows use of shop command"
      economyshop.create:
        default: true
        description: "Allows creating shops"
      economyshop.remove:
        default: true
        description: "Allows removing own shops"
      economyshop.admin:
        default: op
        description: "Allows removing any shop"