name: EconomyAirport
main: onebone\economyairport\EconomyAirport
version: "2.0.0"
author: onebone
api: 5.0.0
depend: [EconomyAPI]

commands:
  airport:
    description: "Airport teleportation command"
    usage: "/airport [add|remove|list|<airport_name>]"
    permission: economyairport.command

permissions:
  economyairport:
    default: op
    description: "Allows access to all EconomyAirport features"
    children:
      economyairport.command:
        default: true
        description: "Allows use of airport command"
      economyairport.admin:
        default: op
        description: "Allows adding and removing airports"