name: EconomyLand
main: onebone\economyland\EconomyLand
version: "2.0.1"
api: 5.0.0

depend: [EconomyAPI]
author: onebone

commands:
 land:
  description: EconomyLand command
  usage: /land
  permission: economyland.command.land
permissions:
 economyland.command:
  description: Allows player to use all of land command
  default: op
  children:
   economyland.command.land:
    description: Allows player to use /land command
    default: true
