name: EconomyLand
main: onebone\economyland\EconomyLand
<<<<<<< HEAD
version: "2.0.0"
=======
api: 5.0.0
version: "3.0.0-SNAPSHOT"
>>>>>>> 1011d39ed1ea3ab6f6329818ddb2078ec03b1144
author: onebone
api: 5.0.0
depend: [EconomyAPI]

commands:
  land:
    description: "Land management command"
    usage: "/land <buy|here|list|invite|move|option|pos1|pos2>"
    permission: economyland.command

permissions:
  economyland:
    default: op
    description: "Allows access to all EconomyLand features"
    children:
      economyland.command:
        default: true
        description: "Allows use of land command"
      economyland.buy:
        default: true
        description: "Allows buying land"
      economyland.admin:
        default: op
        description: "Allows administrative land management"